apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: bbbb-quarkus-app
  description: A cool quarkus app
  annotations:
    argocd/app-name: bbbb-quarkus-app-bootstrap
    backstage.io/kubernetes-id: bbbb-quarkus-app
    # It must be commented otherwise we cannot see the Tekton pipelines resources
    # backstage.io/kubernetes-namespace: tqvarnst
    backstage.io/source-location: url:https://github.com/tqvarnst/bbbb-quarkus-app
    # The janus-idp.io/tekton allows to set the boolean value: isTektonCIAvailable which is used within the UI to enable/disable the TektonCIComponent
    janus-idp.io/tekton: bbbb-quarkus-app
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: tqvarnst/
    # See: topology annotation: https://github.com/janus-idp/backstage-plugins/tree/main/plugins/topology
    app.kubernetes.io/name: quarkus
  tags:
    - java
    - quarkus
  links:
    - url: https://bbbb-quarkus-app-tqvarnst.apps.qshift.snowdrop.dev/
      title: Quarkus application url
      icon: web
spec:
  type: service
  lifecycle: production
  owner: user:default/guest
